const GROQ_API_KEY = import.meta.env.VITE_GROQ_API_KEY;
const GROQ_BASE_URL = import.meta.env.VITE_GROQ_BASE_URL;

export interface EvaluationInput {
  transcript: string;
  description: string;
  targetDurationMinutes: number;
  actualDurationSeconds: number;
  fillerWordCount: number;
  fillerBreakdown: Record<string, number>;
  longPauses: number;
  totalSlides: number;
}

export interface AspectScore {
  name: string;
  score: number;
  maxScore: number;
  feedback: string;
}

export interface EvaluationResult {
  overallScore: number;
  aspects: AspectScore[];
  summary: string;
  strengths: string[];
  improvements: string[];
  wordCount: number;
  wpm: number;
}

export async function evaluatePresentation(
  input: EvaluationInput,
): Promise<EvaluationResult> {
  const wordCount = input.transcript.split(/\s+/).filter(Boolean).length;
  const durationMinutes = input.actualDurationSeconds / 60;
  const wpm = durationMinutes > 0 ? Math.round(wordCount / durationMinutes) : 0;

  const prompt = `You are an expert academic presentation coach at a top university in Indonesia. Evaluate the following student presentation practice session. 
The presentation is in Indonesian language. ALL YOUR FEEDBACK AND RESPONSES MUST BE WRITTEN IN INDONESIAN.

**IMPORTANT GRADING GUIDELINES:**
- The transcript is generated by speech-to-text (STT) technology and may contain typos, misrecognized words, or grammatical errors
- DO NOT penalize heavily for spelling errors, typos, or minor vocabulary mistakes that are likely STT errors
- Focus on CONTENT, STRUCTURE, and DELIVERY PATTERNS rather than perfect spelling
- Be LENIENT with vocabulary scoring - recognize that STT might have misheard technical terms
- Prioritize the MEANING and MESSAGE over exact word accuracy
- Give students benefit of the doubt if a word seems off but meaning is clear

## Context
- **Presentation Topic (described by student):** "${input.description}"
- **Target Duration:** ${input.targetDurationMinutes} minutes
- **Actual Duration:** ${Math.floor(input.actualDurationSeconds / 60)}m ${input.actualDurationSeconds % 60}s
- **Total Slides:** ${input.totalSlides}
- **Words Spoken:** ${wordCount}
- **Words Per Minute (WPM):** ${wpm}
- **Filler Words Used:** ${input.fillerWordCount} times (breakdown: ${JSON.stringify(input.fillerBreakdown)})
- **Long Pauses (>3 seconds):** ${input.longPauses}

## Student's Spoken Transcript (Generated by Speech-to-Text - may contain typos!)
"${input.transcript}"

## Grading Rubric (Score each out of the max points) - BE LENIENT WITH STT ERRORS!

1. **Content Accuracy (25 pts)** 
   - Focus: Does the MEANING match the topic? Are KEY CONCEPTS present?
   - BE LENIENT: Ignore typos and spelling mistakes from STT
   - Look for: Main ideas, key points, logical flow of content
   - Don't penalize: Individual word mistakes, minor terminology errors

2. **Structure & Flow (15 pts)**
   - Focus: Is there intro, body, conclusion? Are transitions clear?
   - Look for: Logical progression, clear sections
   - This is NOT affected by STT errors

3. **Vocabulary & Terminology (15 pts)**
   - **BE VERY LENIENT HERE** - STT often mishears technical terms!
   - Focus: Did student ATTEMPT to use appropriate terms?
   - Look for: Professional tone, technical concepts (even if misspelled)
   - Give HIGH scores if intent is clear, even with errors

4. **Filler Words & Hesitation (15 pts)**
   - Focus: How many "anu", "em", "ee", "kayak" based on provided count
   - Use the provided filler_word_count: ${input.fillerWordCount}
   - Scoring guide: 0-5 fillers = 15pts, 6-15 = 12pts, 16-30 = 9pts, 31+ = 6pts

5. **Pacing & Time Management (15 pts)**
   - Focus: Speed (ideal 100-130 WPM for Indonesian), timing accuracy
   - Current WPM: ${wpm}
   - Duration accuracy: Target ${input.targetDurationMinutes}min, Actual ${Math.floor(input.actualDurationSeconds / 60)}min

6. **Clarity & Confidence (15 pts)**
   - Focus: Sentence patterns, overall confidence tone
   - Look for: Complete thoughts, assertive language
   - DON'T penalize: STT-generated grammar errors

**SCORING PHILOSOPHY:**
- Default to HIGHER scores when in doubt
- Recognize STT limitations
- Focus on delivery and content substance
- Be encouraging and constructive
- Students should average 70-85 range if they made good effort

## Response Format (STRICT JSON ONLY)
Respond with ONLY a valid JSON object, no markdown formatting, no code blocks:
{
  "overallScore": <number 0-100>,
  "aspects": [
    {"name": "Content Accuracy", "score": <number>, "maxScore": 25, "feedback": "<detailed feedback in Indonesian>"},
    {"name": "Structure & Flow", "score": <number>, "maxScore": 15, "feedback": "<detailed feedback in Indonesian>"},
    {"name": "Vocabulary & Terminology", "score": <number>, "maxScore": 15, "feedback": "<detailed feedback in Indonesian>"},
    {"name": "Filler Words & Hesitation", "score": <number>, "maxScore": 15, "feedback": "<detailed feedback in Indonesian>"},
    {"name": "Pacing & Time Management", "score": <number>, "maxScore": 15, "feedback": "<detailed feedback in Indonesian>"},
    {"name": "Clarity & Confidence", "score": <number>, "maxScore": 15, "feedback": "<detailed feedback in Indonesian>"}
  ],
  "summary": "<2-3 sentence overall summary in Indonesian, be encouraging>",
  "strengths": ["<strength 1 in Indonesian>", "<strength 2 in Indonesian>", "<strength 3 in Indonesian>"],
  "improvements": ["<improvement 1 in Indonesian>", "<improvement 2 in Indonesian>", "<improvement 3 in Indonesian>"]
}`;

  // Create AbortController for timeout
  const controller = new AbortController();
  const timeoutId = setTimeout(() => {
    controller.abort();
  }, 45000); // 45 second timeout

  try {
    const response = await fetch(`${GROQ_BASE_URL}/chat/completions`, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Authorization: `Bearer ${GROQ_API_KEY}`,
      },
      body: JSON.stringify({
        model: "openai/gpt-oss-20b",
        messages: [
          {
            role: "system",
            content:
              "You are an academic presentation evaluator. Respond only with valid JSON.",
          },
          { role: "user", content: prompt },
        ],
        temperature: 0.3,
        max_tokens: 2000,
      }),
      signal: controller.signal,
    });

    clearTimeout(timeoutId);

    if (!response.ok) {
      
      // Handle specific error codes
      if (response.status === 429) {
        throw new Error('Terlalu banyak permintaan. Silakan tunggu beberapa saat dan coba lagi.');
      } else if (response.status === 503) {
        throw new Error('Layanan AI sedang sibuk. Silakan coba lagi dalam beberapa saat.');
      } else if (response.status === 401) {
        throw new Error('API key tidak valid. Hubungi administrator.');
      }
      
      throw new Error(
        `AI evaluation failed: ${response.status} ${response.statusText}`,
      );
    }

    const data = await response.json();
    const content = data.choices[0].message.content;

    // Parse the JSON response (strip any accidental markdown fences)
    const cleanContent = content
      .replace(/```json\n?/g, "")
      .replace(/```\n?/g, "")
      .trim();
    
    try {
      const parsed = JSON.parse(cleanContent);
      return {
        ...parsed,
        wordCount,
        wpm,
      };
    } catch (err) {
      throw new Error("AI mengembalikan format data yang tidak valid. Silakan coba lagi.");
    }
  } catch (err: any) {
    clearTimeout(timeoutId);
    
    // Handle AbortError (timeout)
    if (err.name === 'AbortError') {
      throw new Error('AI evaluation timeout setelah 45 detik. Silakan coba lagi dengan transkrip yang lebih pendek.');
    }
    
    // Handle network errors
    if (err.message.includes('Failed to fetch') || err.message.includes('NetworkError')) {
      throw new Error('Gagal terhubung ke server AI. Periksa koneksi internet Anda.');
    }
    
    // Re-throw other errors
    throw err;
  }
}
