export { default as Navbar } from './components/Navbar';
export { default as HeroSection } from './components/HeroSection';
export { default as ValuePropSection } from './components/ValuePropSection';
export { default as FeaturesSection } from './components/FeaturesSection';
export { default as HowItWorksSection } from './components/HowItWorksSection';
export { default as FAQSection } from './components/FAQSection';
export { default as CTASection } from './components/CTASection';
export { default as Footer } from './components/Footer';
export { default as LandingPage } from './routes/LandingPage';
